# Generated by Django 2.1.7 on 2019-02-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
