# Generated by Django 2.1.7 on 2019-02-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='maximum_units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='minimum_units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
